/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import static Classes.Main.promedioGanancias1;
import static Classes.Main.promedioGanancias2;
import static Classes.Main.promedioGastos1;
import static Classes.Main.promedioGastos2;
import static Classes.Main.promedioNumTotalTelef1;
import static Classes.Main.promedioNumTotalTelef2;
import static Classes.Main.promedioTelefGanancias1;
import static Classes.Main.promedioTelefGanancias2;
import java.awt.BorderLayout;
import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author massimo
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        generar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 510, 310));

        generar.setText("Generar");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });
        jPanel1.add(generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 730, -1, -1));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 490, 310));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 510, 320));
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 480, 320));

        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        // TODO add your handling code here:
        
        //Telefonos vendidos
        int telefonosProducidosPlanta1=promedioNumTotalTelef1;
        int telefonosProducidosPlanta2=promedioNumTotalTelef2;
       
        
        DefaultCategoryDataset datos = new DefaultCategoryDataset();
        
        datos.setValue(telefonosProducidosPlanta1, "Planta 1", "");
  
        
        datos.setValue(telefonosProducidosPlanta2, "Planta 2", "");
     
        
        JFreeChart grafico_barras = ChartFactory.createBarChart3D(
                "Telefonos Producidos", 
                "Plantas", 
                "Numero de telefonos", 
                datos, 
                PlotOrientation.VERTICAL, 
                true, 
                true, 
                false
        );
        
        
        ChartPanel panel = new ChartPanel(grafico_barras);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(500,300));
        
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(panel,BorderLayout.NORTH);
        
        pack();
        repaint();
        
        
        //Ganancia telefonos
        int gananciaTelefonosPlanta1=promedioTelefGanancias1;
        int gananciaTelefonosPlanta2=promedioTelefGanancias2;
       
        
        DefaultCategoryDataset datos2 = new DefaultCategoryDataset();
        
        datos2.setValue(gananciaTelefonosPlanta1, "Planta 1", "");
  
        
        datos2.setValue(gananciaTelefonosPlanta2, "Planta 2", "");
     
        
        JFreeChart grafico_barras2 = ChartFactory.createBarChart3D(
                "Ganancia Telefonos", 
                "Plantas", 
                "Dolares", 
                datos2, 
                PlotOrientation.VERTICAL, 
                true, 
                true, 
                false
        );
        
        
        ChartPanel panel2 = new ChartPanel(grafico_barras2);
        panel2.setMouseWheelEnabled(true);
        panel2.setPreferredSize(new Dimension(500,300));
        
        jPanel3.setLayout(new BorderLayout());
        jPanel3.add(panel2,BorderLayout.NORTH);
        
        pack();
        repaint();
        
        //Gastos Sueldos
        int gastosSueldosPlanta1 = promedioGastos1;
        int gastosSueldosPlanta2= promedioGastos2;
       
        
        DefaultCategoryDataset datos3 = new DefaultCategoryDataset();
        
        datos3.setValue(gastosSueldosPlanta1, "Planta 1", "");
  
        
        datos3.setValue(gastosSueldosPlanta2, "Planta 2", "");
     
        
        JFreeChart grafico_barras3 = ChartFactory.createBarChart3D(
                "Gastos Salarios", 
                "Plantas", 
                "Dolares", 
                datos3, 
                PlotOrientation.VERTICAL, 
                true, 
                true, 
                false
        );
        
        
        ChartPanel panel3 = new ChartPanel(grafico_barras3);
        panel3.setMouseWheelEnabled(true);
        panel3.setPreferredSize(new Dimension(500,300));
        
        jPanel4.setLayout(new BorderLayout());
        jPanel4.add(panel3,BorderLayout.NORTH);
        
        pack();
        repaint();
        
        
        //Ganancia Neta 
        int gananciaNetaPlanta1=promedioGanancias1;
        int gananciaNetaPlanta2=promedioGanancias2;
       
        
        DefaultCategoryDataset datos4 = new DefaultCategoryDataset();
        
        datos4.setValue(gananciaNetaPlanta1, "Planta 1", "");
  
        
        datos4.setValue(gananciaNetaPlanta2, "Planta 2", "");
     
        
        JFreeChart grafico_barras4 = ChartFactory.createBarChart3D(
                "Ganancia Neta", 
                "Plantas", 
                "Dolares", 
                datos4, 
                PlotOrientation.VERTICAL, 
                true, 
                true, 
                false
        );
        
        
        ChartPanel panel4 = new ChartPanel(grafico_barras4);
        panel4.setMouseWheelEnabled(true);
        panel4.setPreferredSize(new Dimension(500,300));
        
        jPanel5.setLayout(new BorderLayout());
        jPanel5.add(panel4,BorderLayout.NORTH);
        
        pack();
        repaint();
        
    }//GEN-LAST:event_generarActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton generar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
