/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jose Rubin
 */
public class InterfazPlantas extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPlantas
     */
    public int numProducBotJ;
    public InterfazPlantas() {
        initComponents();
        this.setLocationRelativeTo(null);
        Ensambladores1.setEditable(false);
        this.numProducBotJ = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        TextGerentePlanta3 = new javax.swing.JTextField();
        TextJefePlanta3 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        TextJefePlanta5 = new javax.swing.JTextField();
        TextGerentePlanta4 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        TextJefePlanta6 = new javax.swing.JTextField();
        TiempoDias = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        UltimoLote1 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        GastosSalario2 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        GananciasTotales1 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        GananciasTotales2 = new javax.swing.JTextField();
        GastosSalario5 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        UltimoLote2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonSumBotones2 = new javax.swing.JButton();
        BotonSumCams2 = new javax.swing.JButton();
        BotonSumPant2 = new javax.swing.JButton();
        BotonMenosBotones2 = new javax.swing.JButton();
        BotonMenosPant2 = new javax.swing.JButton();
        BotonMenosCams2 = new javax.swing.JButton();
        ProductoresCams2 = new javax.swing.JTextField();
        ProductoresB2 = new javax.swing.JTextField();
        ProductoresPant2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProductoresPines2 = new javax.swing.JTextField();
        BotonSumPines2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        BotonMenosPines2 = new javax.swing.JButton();
        AlmacenCamsP2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        AlmacenBotonesP2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        AlmacenPantallasP2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        AlmacenPinesP2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        TelefonosPlanta2 = new javax.swing.JTextField();
        BotonSumEnsam2 = new javax.swing.JButton();
        Ensambladores2 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        BotonMenosEnsam2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        BotonSumBotones1 = new javax.swing.JButton();
        BotonSumCams1 = new javax.swing.JButton();
        BotonSumPant1 = new javax.swing.JButton();
        BotonMenosBotones1 = new javax.swing.JButton();
        BotonMenosPant1 = new javax.swing.JButton();
        BotonMenosCams1 = new javax.swing.JButton();
        ProductoresCams1 = new javax.swing.JTextField();
        ProductoresB1 = new javax.swing.JTextField();
        ProductoresPant1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ProductoresPines1 = new javax.swing.JTextField();
        BotonSumPines1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        BotonMenosPines1 = new javax.swing.JButton();
        TelefonosPlanta1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        AlmacenPantallasP1 = new javax.swing.JTextField();
        AlmacenPinesP1 = new javax.swing.JTextField();
        AlmacenBotonesP1 = new javax.swing.JTextField();
        AlmacenCamsP1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Ensambladores1 = new javax.swing.JTextField();
        BotonSumEnsam1 = new javax.swing.JButton();
        BotonMenosEnsam1 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField9.setText("jTextField1");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-380, 250, 250, 30));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField10.setText("jTextField1");
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-380, 250, 250, 30));

        TextGerentePlanta3.setText("Durmiendo....");
        jPanel2.add(TextGerentePlanta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 740, 250, 30));

        TextJefePlanta3.setText("Durmiendo....");
        jPanel2.add(TextJefePlanta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, 250, 30));
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, -1, -1));

        jLabel48.setText("Jefe Planta 2");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 660, -1, -1));

        jLabel49.setText("Gerente Planta 2");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 720, -1, -1));

        jLabel50.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel50.setText("Countdown");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 110, -1));

        TextJefePlanta5.setText("1");
        TextJefePlanta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextJefePlanta5ActionPerformed(evt);
            }
        });
        jPanel2.add(TextJefePlanta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 30, 40));

        TextGerentePlanta4.setText("Durmiendo....");
        TextGerentePlanta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextGerentePlanta4ActionPerformed(evt);
            }
        });
        jPanel2.add(TextGerentePlanta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, 250, 30));

        jLabel51.setText("Gerente Planta 1");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 600, -1, -1));

        jLabel52.setText("Jefe Planta 1");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, -1, -1));

        TextJefePlanta6.setText("Durmiendo....");
        TextJefePlanta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextJefePlanta6ActionPerformed(evt);
            }
        });
        jPanel2.add(TextJefePlanta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 250, 30));

        TiempoDias.setText("1");
        TiempoDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempoDiasActionPerformed(evt);
            }
        });
        jPanel2.add(TiempoDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 30, 40));

        jLabel53.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel53.setText("Tiempo de los Dias");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 160, -1));

        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, 180, 110));

        jLabel56.setText("Telefonos Vendidos Ultimo Lote");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        UltimoLote1.setText("Money");
        UltimoLote1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimoLote1ActionPerformed(evt);
            }
        });
        jPanel2.add(UltimoLote1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 110, 30));

        jLabel57.setText("Gastos en Salarios Planta 2");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, -1, -1));

        GastosSalario2.setText("Durmiendo....");
        GastosSalario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GastosSalario2ActionPerformed(evt);
            }
        });
        jPanel2.add(GastosSalario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 250, 30));

        jLabel58.setText("Ganancia Total Planta 1");
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, -1, -1));

        GananciasTotales1.setText("Money");
        GananciasTotales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GananciasTotales1ActionPerformed(evt);
            }
        });
        jPanel2.add(GananciasTotales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 680, 250, 30));

        jLabel59.setText("Ganancia Total Planta 2");
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 720, -1, -1));

        GananciasTotales2.setText("Durmiendo....");
        GananciasTotales2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GananciasTotales2ActionPerformed(evt);
            }
        });
        jPanel2.add(GananciasTotales2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 740, 250, 30));

        GastosSalario5.setText("Money");
        GastosSalario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GastosSalario5ActionPerformed(evt);
            }
        });
        jPanel2.add(GastosSalario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 250, 30));

        jLabel60.setText("Gastos en Salarios Planta 1");
        jPanel2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, -1));

        jLabel61.setText("Telefonos Vendidos Ultimo Lote");
        jPanel2.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, -1, -1));

        UltimoLote2.setText("Money");
        UltimoLote2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimoLote2ActionPerformed(evt);
            }
        });
        jPanel2.add(UltimoLote2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 110, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Planta 2");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        BotonSumBotones2.setText("+");
        jPanel3.add(BotonSumBotones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 60, 50));

        BotonSumCams2.setText("+");
        jPanel3.add(BotonSumCams2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 60, 50));

        BotonSumPant2.setText("+");
        jPanel3.add(BotonSumPant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 60, 50));

        BotonMenosBotones2.setText("-");
        BotonMenosBotones2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenosBotones2ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonMenosBotones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 60, 50));

        BotonMenosPant2.setText("-");
        BotonMenosPant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenosPant2ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonMenosPant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 60, 50));

        BotonMenosCams2.setText("-");
        BotonMenosCams2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenosCams2ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonMenosCams2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 60, 50));

        ProductoresCams2.setText("1");
        jPanel3.add(ProductoresCams2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 250, 30));

        ProductoresB2.setText("1");
        jPanel3.add(ProductoresB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 250, 30));

        ProductoresPant2.setText("1");
        jPanel3.add(ProductoresPant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 250, 30));

        jLabel3.setText("Productores de Camaras");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel4.setText("Productores de Botones");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel5.setText("Productores de Pantallas");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        ProductoresPines2.setText("1");
        jPanel3.add(ProductoresPines2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 250, 30));

        BotonSumPines2.setText("+");
        jPanel3.add(BotonSumPines2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 60, 50));

        jLabel6.setText("Productores de Pines de Carga");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        BotonMenosPines2.setText("-");
        BotonMenosPines2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenosPines2ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonMenosPines2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 60, 50));

        AlmacenCamsP2.setText("1");
        jPanel3.add(AlmacenCamsP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 20, 20));

        jLabel28.setText("Botones");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        AlmacenBotonesP2.setText("1");
        jPanel3.add(AlmacenBotonesP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 20, 20));

        jLabel29.setText("Pantallas");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        AlmacenPantallasP2.setText("1");
        AlmacenPantallasP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmacenPantallasP2ActionPerformed(evt);
            }
        });
        jPanel3.add(AlmacenPantallasP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 20, 20));

        jLabel30.setText("Pines de Carga");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        AlmacenPinesP2.setText("1");
        AlmacenPinesP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmacenPinesP2ActionPerformed(evt);
            }
        });
        jPanel3.add(AlmacenPinesP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 20, 20));

        jLabel31.setText("Camaras");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        jLabel32.setText("Telefonos");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, -1));

        TelefonosPlanta2.setText("1");
        TelefonosPlanta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonosPlanta2ActionPerformed(evt);
            }
        });
        jPanel3.add(TelefonosPlanta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 70, 30));

        BotonSumEnsam2.setText("+");
        BotonSumEnsam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumEnsam2ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonSumEnsam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 60, 50));

        Ensambladores2.setText("1");
        Ensambladores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ensambladores2ActionPerformed(evt);
            }
        });
        jPanel3.add(Ensambladores2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 250, 30));

        jLabel55.setText("Ensambladores");
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        BotonMenosEnsam2.setText("-");
        BotonMenosEnsam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenosEnsam2ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonMenosEnsam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 60, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 560, 440));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Planta 1");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, -1));

        BotonSumBotones1.setText("+");
        jPanel4.add(BotonSumBotones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 60, 50));

        BotonSumCams1.setText("+");
        jPanel4.add(BotonSumCams1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 60, 50));

        BotonSumPant1.setText("+");
        jPanel4.add(BotonSumPant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 60, 50));

        BotonMenosBotones1.setText("-");
        BotonMenosBotones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenosBotones1ActionPerformed(evt);
            }
        });
        jPanel4.add(BotonMenosBotones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, 50));

        BotonMenosPant1.setText("-");
        BotonMenosPant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenosPant1ActionPerformed(evt);
            }
        });
        jPanel4.add(BotonMenosPant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 60, 50));

        BotonMenosCams1.setText("-");
        BotonMenosCams1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenosCams1ActionPerformed(evt);
            }
        });
        jPanel4.add(BotonMenosCams1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 60, 50));

        ProductoresCams1.setText("1");
        jPanel4.add(ProductoresCams1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 250, 30));

        ProductoresB1.setText("1");
        ProductoresB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoresB1ActionPerformed(evt);
            }
        });
        jPanel4.add(ProductoresB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 250, 30));

        ProductoresPant1.setText("1");
        jPanel4.add(ProductoresPant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 250, 30));

        jLabel12.setText("Productores de Camaras");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel13.setText("Pines de Carga");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        jLabel14.setText("Productores de Pantallas");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        ProductoresPines1.setText("1");
        jPanel4.add(ProductoresPines1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 250, 30));

        BotonSumPines1.setText("+");
        jPanel4.add(BotonSumPines1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 60, 50));

        jLabel15.setText("Productores de Pines de Carga");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        BotonMenosPines1.setText("-");
        BotonMenosPines1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenosPines1ActionPerformed(evt);
            }
        });
        jPanel4.add(BotonMenosPines1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 60, 50));

        TelefonosPlanta1.setText("1");
        TelefonosPlanta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonosPlanta1ActionPerformed(evt);
            }
        });
        jPanel4.add(TelefonosPlanta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 70, 30));

        jLabel22.setText("Productores de Botones");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        AlmacenPantallasP1.setText("1");
        AlmacenPantallasP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmacenPantallasP1ActionPerformed(evt);
            }
        });
        jPanel4.add(AlmacenPantallasP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 20, 20));

        AlmacenPinesP1.setText("1");
        jPanel4.add(AlmacenPinesP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 20, 20));

        AlmacenBotonesP1.setText("1");
        jPanel4.add(AlmacenBotonesP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 20, 20));

        AlmacenCamsP1.setText("1");
        jPanel4.add(AlmacenCamsP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 20, 20));

        jLabel24.setText("Telefonos");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, -1));

        jLabel25.setText("Camaras");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        jLabel26.setText("Pantallas");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        jLabel27.setText("Botones");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        Ensambladores1.setText("1");
        Ensambladores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ensambladores1ActionPerformed(evt);
            }
        });
        jPanel4.add(Ensambladores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 250, 30));

        BotonSumEnsam1.setText("+");
        BotonSumEnsam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumEnsam1ActionPerformed(evt);
            }
        });
        jPanel4.add(BotonSumEnsam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 60, 50));

        BotonMenosEnsam1.setText("-");
        BotonMenosEnsam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenosEnsam1ActionPerformed(evt);
            }
        });
        jPanel4.add(BotonMenosEnsam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 60, 50));

        jLabel54.setText("Ensambladores");
        jPanel4.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 440));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMenosEnsam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenosEnsam1ActionPerformed
        // TODO add your handling code here:
        // Botones Menos
        if(numProducBotJ > 1){
            numProducBotJ--;
            Ensambladores1.setText(Integer.toString(numProducBotJ));
        }
    }//GEN-LAST:event_BotonMenosEnsam1ActionPerformed

    private void BotonSumEnsam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumEnsam1ActionPerformed
        // TODO add your handling code here:
        numProducBotJ++;
        Ensambladores1.setText(Integer.toString(numProducBotJ));
    }//GEN-LAST:event_BotonSumEnsam1ActionPerformed

    private void Ensambladores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ensambladores1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ensambladores1ActionPerformed

    private void AlmacenPantallasP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmacenPantallasP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlmacenPantallasP1ActionPerformed

    private void TelefonosPlanta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonosPlanta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonosPlanta1ActionPerformed

    private void BotonMenosPines1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenosPines1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenosPines1ActionPerformed

    private void ProductoresB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoresB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoresB1ActionPerformed

    private void BotonMenosCams1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenosCams1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenosCams1ActionPerformed

    private void BotonMenosPant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenosPant1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenosPant1ActionPerformed

    private void BotonMenosBotones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenosBotones1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenosBotones1ActionPerformed

    private void BotonMenosEnsam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenosEnsam2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenosEnsam2ActionPerformed

    private void Ensambladores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ensambladores2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ensambladores2ActionPerformed

    private void BotonSumEnsam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumEnsam2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSumEnsam2ActionPerformed

    private void TelefonosPlanta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonosPlanta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonosPlanta2ActionPerformed

    private void AlmacenPinesP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmacenPinesP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlmacenPinesP2ActionPerformed

    private void AlmacenPantallasP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmacenPantallasP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlmacenPantallasP2ActionPerformed

    private void BotonMenosPines2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenosPines2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenosPines2ActionPerformed

    private void BotonMenosCams2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenosCams2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenosCams2ActionPerformed

    private void BotonMenosPant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenosPant2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenosPant2ActionPerformed

    private void BotonMenosBotones2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenosBotones2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMenosBotones2ActionPerformed

    private void UltimoLote2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoLote2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UltimoLote2ActionPerformed

    private void GastosSalario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GastosSalario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GastosSalario5ActionPerformed

    private void GananciasTotales2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GananciasTotales2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GananciasTotales2ActionPerformed

    private void GananciasTotales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GananciasTotales1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GananciasTotales1ActionPerformed

    private void GastosSalario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GastosSalario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GastosSalario2ActionPerformed

    private void UltimoLote1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoLote1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UltimoLote1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TiempoDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoDiasActionPerformed

    private void TextJefePlanta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextJefePlanta6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextJefePlanta6ActionPerformed

    private void TextGerentePlanta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextGerentePlanta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextGerentePlanta4ActionPerformed

    private void TextJefePlanta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextJefePlanta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextJefePlanta5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPlantas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlmacenBotonesP1;
    private javax.swing.JTextField AlmacenBotonesP2;
    private javax.swing.JTextField AlmacenCamsP1;
    private javax.swing.JTextField AlmacenCamsP2;
    private javax.swing.JTextField AlmacenPantallasP1;
    private javax.swing.JTextField AlmacenPantallasP2;
    private javax.swing.JTextField AlmacenPinesP1;
    private javax.swing.JTextField AlmacenPinesP2;
    private javax.swing.JButton BotonMenosBotones1;
    private javax.swing.JButton BotonMenosBotones2;
    private javax.swing.JButton BotonMenosCams1;
    private javax.swing.JButton BotonMenosCams2;
    private javax.swing.JButton BotonMenosEnsam1;
    private javax.swing.JButton BotonMenosEnsam2;
    private javax.swing.JButton BotonMenosPant1;
    private javax.swing.JButton BotonMenosPant2;
    private javax.swing.JButton BotonMenosPines1;
    private javax.swing.JButton BotonMenosPines2;
    private javax.swing.JButton BotonSumBotones1;
    private javax.swing.JButton BotonSumBotones2;
    private javax.swing.JButton BotonSumCams1;
    private javax.swing.JButton BotonSumCams2;
    private javax.swing.JButton BotonSumEnsam1;
    private javax.swing.JButton BotonSumEnsam2;
    private javax.swing.JButton BotonSumPant1;
    private javax.swing.JButton BotonSumPant2;
    private javax.swing.JButton BotonSumPines1;
    private javax.swing.JButton BotonSumPines2;
    private javax.swing.JTextField Ensambladores1;
    private javax.swing.JTextField Ensambladores2;
    private javax.swing.JTextField GananciasTotales1;
    private javax.swing.JTextField GananciasTotales2;
    private javax.swing.JTextField GastosSalario2;
    private javax.swing.JTextField GastosSalario5;
    private javax.swing.JTextField ProductoresB1;
    private javax.swing.JTextField ProductoresB2;
    private javax.swing.JTextField ProductoresCams1;
    private javax.swing.JTextField ProductoresCams2;
    private javax.swing.JTextField ProductoresPant1;
    private javax.swing.JTextField ProductoresPant2;
    private javax.swing.JTextField ProductoresPines1;
    private javax.swing.JTextField ProductoresPines2;
    private javax.swing.JTextField TelefonosPlanta1;
    private javax.swing.JTextField TelefonosPlanta2;
    private javax.swing.JTextField TextGerentePlanta3;
    private javax.swing.JTextField TextGerentePlanta4;
    private javax.swing.JTextField TextJefePlanta3;
    private javax.swing.JTextField TextJefePlanta5;
    private javax.swing.JTextField TextJefePlanta6;
    private javax.swing.JTextField TiempoDias;
    private javax.swing.JTextField UltimoLote1;
    private javax.swing.JTextField UltimoLote2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
